title: Liderazgo en modo debug
logo: /assets/img/logo-blog.png
description: Para los que ejecutan. Los que aprenden. Los que lideran con dudas y aún así, avanzan.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
