title: Liderazgo en modo debug
logo: /assets/img/logo.png
description: Para los que ejecutan. Los que aprenden. Los que lideran con dudas y aún así, avanzan.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
site.github.owner_url: https://www.linkedin.com/rodrigolopezguerra 
